[package]
name = "concourse-jsonschema-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
peg = "0.8.0"
itertools = "0.10.3"
clap = { version = "3.2.8", features = ["derive"] }
regex = "1.6.0"