name: Update Schema

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout generator
        uses: actions/checkout@v5

      - name: Checkout concourse/docs
        uses: actions/checkout@v5
        with:
          repository: concourse/docs
          path: concourse-docs

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq
          version: 1.0

      - name: Build schema generator
        run: cargo build --release

      - name: Generate new schema
        run: |
          shopt -s globstar
          ./target/release/concourse-jsonschema-generator concourse-docs/lit/docs/**/*.lit | jq . > generated_schema.json

      - name: Safety check on generated schema
        run: |
          LINES=$(wc -l < generated_schema.json)
          if [ "$LINES" -lt 500 ]; then
            echo "Error: Generated schema has only $LINES lines, which is below the safety threshold of 500."
            exit 1
          fi
          echo "Generated schema has $LINES lines, which is above the safety threshold."

      - name: Check for changes
        id: diff
        run: |
          if ! diff -q schema.json generated_schema.json; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Commit and push if changed
        if: steps.diff.outputs.changed == 'true'
        run: |
          mv generated_schema.json schema.json
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add schema.json
          git commit -m "docs: auto-update schema.json"
          git push
